force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
                <default>true</default>
                <label>Ativo</label>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
            <value>
                <fullName>Fora de estoque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>REVIEW-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReviewTriggerHandler.cls
public with sharing class ReviewTriggerHandler {
    public static void handler(){

        Set<Id> productIds = new Set<Id>();

        if(Trigger.isInsert){
            for(Review__c review : Trigger.new){
                if(review.Status__c == 'Aprovado'){
                    productIds.add(review.Product__c);
                }
            }
        }
        if(Trigger.isUpdate){
            for(Review__c review : Trigger.new){
                Review__c oldReview = Trigger.oldMap.get(review.Id);
                if(review.Status__c != oldReview.Status__c || review.Rating__c != oldReview.Rating__c){
                    productIds.add(review.Product__c);
                }
            }
        }
        if(Trigger.isDelete){
            for(Review__c review : Trigger.old){
                if(review.Status__c == 'Aprovado'){
                    productIds.add(review.Product__c);
                }
            }
        }
        if(Trigger.isUndelete){
            for(Review__c review : Trigger.new){
                if(review.Status__c == 'Aprovado'){
                    productIds.add(review.Product__c);
                }
            }
        }
        if(!productIds.isEmpty()){
            //ainda para completar
        }
    }
}